"""Objetos e decisões do domínio de consulta da arquitetura v0.2."""

from consultor_juridico.domain.consultation import (
    AnswerDraft,
    Citation,
    ClarificationRequest,
    ClarificationTurn,
    ConsultationOutcome,
    ConsultationResult,
    Interpretation,
    Question,
)
from consultor_juridico.domain.corpus import (
    CorpusIdentityConflict,
    DuplicateProvisionStableKey,
    ParsedAct,
    ParsedCorpus,
    ParsedMetadata,
    ParsedProvision,
    ProvisionType,
    SearchUnitDraft,
    SearchUnitType,
    SourceCapture,
    SourceSnapshotIntegrityError,
    SourceSnapshotNotFound,
    act_version_hash,
    provision_stable_key,
    search_unit_hash,
)
from consultor_juridico.domain.decisions import (
    AbstainOutcome,
    AnswerOutcome,
    CitationValidation,
    ClarificationOutcome,
    ConsultationDecisionKind,
    ConsultationModelOutcome,
)
from consultor_juridico.domain.evidence import (
    CitationItem,
    EvidenceCandidate,
    SelectedEvidence,
)

__all__ = [
    "AbstainOutcome",
    "AnswerOutcome",
    "AnswerDraft",
    "Citation",
    "CitationItem",
    "CitationValidation",
    "ClarificationOutcome",
    "ClarificationRequest",
    "ClarificationTurn",
    "ConsultationOutcome",
    "ConsultationDecisionKind",
    "ConsultationModelOutcome",
    "ConsultationResult",
    "CorpusIdentityConflict",
    "EvidenceCandidate",
    "DuplicateProvisionStableKey",
    "ParsedAct",
    "ParsedCorpus",
    "ParsedMetadata",
    "ParsedProvision",
    "ProvisionType",
    "Interpretation",
    "Question",
    "SearchUnitDraft",
    "SearchUnitType",
    "SelectedEvidence",
    "SourceCapture",
    "SourceSnapshotIntegrityError",
    "SourceSnapshotNotFound",
    "act_version_hash",
    "provision_stable_key",
    "search_unit_hash",
]
